// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeymhwaAsTNIOwPJiHHAk3uGHy5pdaO6o',
    appId: '1:1011569368397:web:68550e79bd4bceb4362b04',
    messagingSenderId: '1011569368397',
    projectId: 'fruits-store-2a1a8',
    authDomain: 'fruits-store-2a1a8.firebaseapp.com',
    storageBucket: 'fruits-store-2a1a8.firebasestorage.app',
    measurementId: 'G-9LGMG7NQVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP2nG1sVMOC6c65zXRjYScqItkolG9SAM',
    appId: '1:1011569368397:android:0c778e94c4811633362b04',
    messagingSenderId: '1011569368397',
    projectId: 'fruits-store-2a1a8',
    storageBucket: 'fruits-store-2a1a8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeymhwaAsTNIOwPJiHHAk3uGHy5pdaO6o',
    appId: '1:1011569368397:web:3ff34f592450aeff362b04',
    messagingSenderId: '1011569368397',
    projectId: 'fruits-store-2a1a8',
    authDomain: 'fruits-store-2a1a8.firebaseapp.com',
    storageBucket: 'fruits-store-2a1a8.firebasestorage.app',
    measurementId: 'G-SCMR543Z43',
  );
}
